#!/usr/bin/env python
"""Command to verify host is configured correctly for container tools"""

import argparse
import logging
import os
import sys

from checking import Checker

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Command to verify container configuration on host",
        add_help=True
    )
    parser.add_argument(
        '-d', '--debug', action='store_true', help='Turn on debug logging'
    )
    parser.add_argument(
        '-c',
        '--checks',
        nargs='?',
        default='./checks',
        help='Path to checks to execute'
    )
    args = parser.parse_args()

    level = logging.DEBUG if args.debug else logging.INFO
    logging.basicConfig(
        level=level, format='%(asctime)s | %(levelname)-7s | %(message)s'
    )
    logging.debug(
        'Logging initialized at level {}'.format(
            logging.getLevelName(logging.getLogger().getEffectiveLevel())
        )
    )

    if not os.path.isdir(args.checks):
        logging.error("{} is not an existing directory".format(args.checks))
        sys.exit(1)

    sys.exit(0 if Checker().check(args.checks, args.debug) else 2)
