#!/bin/bash

# Basic information and example of bash script
source checking/utils.sh

echo Host OS Version: $(cat /host/etc/redhat-release)
echo Container OS Version: $(cat /etc/redhat-release)

log::debug PATH=$PATH

exit 0
