#!/usr/bin/env python

import errno
import sys

from checking.utils import Rpm, Selinux

# If package is not installed fail fast and early
try:
    Rpm.verify('container-selinux')
except OSError as e:
    sys.stderr.write(e.strerror)
    if e.errno == errno.ENOENT:
        sys.exit(1)


# Check that files on the host are as expected
FILES = [
    '/usr/share/selinux/devel',
    '/usr/share/selinux/devel/include',
    '/usr/share/selinux/devel/include/services',
    '/usr/share/selinux/devel/include/services/container.if',
    '/usr/share/selinux/packages',
    '/usr/share/selinux/packages/container.pp.bz2',
]

error = False
for path in FILES:
    try:
        # Side effect: The existance of the 'path' will also be verified
        Selinux.verify(path)
    except OSError as e:
        sys.stderr.write('  {}\n'.format(str(e)))
        error = True
        continue

if not Selinux.is_enabled():
    sys.stderr.write('selinux enforcing is OFF\n')

sys.exit(0 if not error else 1)
