#!/usr/bin/env python

import errno
import sys

from checking.utils import Rpm, Selinux, Systemd, log_error

# will be set to True on any failed confirm
error = False
FILES = []


def confirm(boolean, message):
    global error
    if not boolean:
        error = True
        log_error(message)


try:
    rpm = Rpm('cri-o')
    rpm.verify()
    FILES = rpm.files
except OSError as e:
    log_error(e.strerror)
    if e.errno == errno.ENOENT:
        error = True

selinux = Selinux()
for path in FILES:
    try:
        # Side effect: The existance of the 'path' will also be verified
        selinux.verify(path)
    except OSError as e:
        log_error(e)
        error = True
        continue

service = Systemd('crio.service')
confirm(service.isactive(), 'crio.service is not active')
confirm(service.isenabled(), 'crio.service is not enabled')

sys.exit(0 if not error else 1)
