#!/usr/bin/env python

import sys

import docker

from checking.utils import log_error

error = False


def confirm(boolean, message):
    global error
    if not boolean:
        error = True
        log_error(message)


client = docker.DockerClient(
    base_url='unix://host/var/run/docker.sock', version='auto'
)

for container in client.containers.list():
    confirm(
        container.attrs['Config']['User'],
        'Container "{}" running as "root"'.format(container.name)
    )

sys.exit(0 if not error else 1)
