#!/usr/bin/env python

from contextlib import closing

from docker import DockerClient

from checking.utils import Checked

with Checked() as (confirm, _):
    with closing(DockerClient(base_url='unix://host/var/run/docker.sock',
                              version='auto')) as client:
        for container in client.containers.list():
            confirm(
                container.attrs['Config']['User'],
                'Container "{}" running as "root"'.format(container.name)
            )
