#!/usr/bin/env python

from checking.utils import Checked, Rpm, Selinux

FILES = []

with Checked() as (confirm, error):
    with Rpm('runc') as rpm:
        if rpm.verify():
            FILES.extend(rpm.files)
        else:
            error(True)

    if not Selinux().verify(*FILES):
        error(True)
