#!/usr/bin/env python

import sys

from checking.utils import Rpm, Selinux

# will be set to True on any failed confirm
error = False
FILES = []

with Rpm('runc') as rpm:
    if rpm.verify():
        FILES.extend(rpm.files)
    else:
        error = True

selinux = Selinux()
for path in FILES:
    error |= not selinux.verify(path)

sys.exit(0 if not error else 1)
