#!/usr/bin/env python

import errno
import sys

from checking.utils import Rpm, Selinux, log_error

# If package is not installed fail fast and early
try:
    Rpm.verify('container-selinux')
except OSError as e:
    log_error(e.strerror)
    if e.errno == errno.ENOENT:
        sys.exit(1)


# Check that files on the host are as expected
FILES = [
    '/usr/share/selinux/devel',
    '/usr/share/selinux/devel/include',
    '/usr/share/selinux/devel/include/services',
    '/usr/share/selinux/devel/include/services/container.if',
    '/usr/share/selinux/packages',
    '/usr/share/selinux/packages/container.pp.bz2',
]

error = False
for path in FILES:
    try:
        # Side effect: The existance of the 'path' will also be verified
        Selinux.verify(path)
    except OSError as e:
        log_error(e)
        error = True
        continue

if not Selinux.is_enabled():
    log_error('selinux enforcing is OFF')

sys.exit(0 if not error else 1)
